# Setup
version_name: nyu_swinL
out_dir: "./outputs/"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 8
ACCUMULATION_STEPS: 4
valBatch: 6
nworkers: 2
ignore_index: 255

feauture_sizes: [[14,18],[28,36],[56,72],[112,144]]

# hypher para
#* Stage Enhanced
compress_r: 4    
hp_r: 4
lp_r: 4

#* Global Perception
attn_dim_r: 2
attn_hp_r: 2

#* Task Fusion


# Optimizer and scheduler
intermediate_supervision: True
aux_loss_weight: 1   

val_interval: 1000
epochs: 99999
max_iter: 40000
optimizer: adamw
optimizer_kwargs:
   lr: 0.00001  
   weight_decay: 0.000001    
scheduler: poly


# Model
model: HiFAN
backbone: swin_large

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_scheme: log
   loss_weights:
       semseg: 1.0
       depth: 1.0
       edge: 1.0
       normals: 1.0